# Generated by Django 6.0.6 on 2026-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponibile', models.BooleanField(default=True)),
            ],
        ),
    ]
