# Generated by Django 6.0.5 on 2026-05-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome prodotto')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo (€)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='negozio.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['prezzo'],
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='negozio.prodotto', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data'],
            },
        ),
    ]
