# Generated by Django 6.0.5 on 2026-05-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negozio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='prodotto',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='quantita',
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negozio.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negozio.prodotto')),
            ],
            options={
                'verbose_name': 'Ordine Prodotto',
                'verbose_name_plural': 'Ordini Prodotti',
            },
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotti',
            field=models.ManyToManyField(related_name='ordini', through='negozio.OrdineProdotto', to='negozio.prodotto', verbose_name='Prodotti'),
        ),
    ]
