# Generated by Django 6.0.6 on 2026-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_categoria_alter_prodotto_options_prodotto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='prodotto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ecommerce.tag'),
        ),
    ]
