# Generated by Django 6.0.4 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibile', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
    ]
