"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wl_-i4=)o)@gc&gr-!k3==70^j&3j=2xqe)*zhhs8z@_b%j4d+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libri',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173"
]

REST_FRAMEWORK = {

    # Classi usate per identificare l'utente che fa la richiesta
    "DEFAULT_AUTHENTICATION_CLASSES": [

        # Autenticazione tramite token nell'header Authorization
        "rest_framework.authentication.TokenAuthentication",

        # Autenticazione tramite sessione Django (utile per la Browsable API)
        "rest_framework.authentication.SessionAuthentication",

    ],


    # Classi usate per decidere se l'utente può accedere alla risorsa
    "DEFAULT_PERMISSION_CLASSES": [

        # Solo gli utenti autenticati possono accedere agli endpoint
        "rest_framework.permissions.IsAuthenticated",

    ],


    # Classe usata per suddividere le liste di risultati in pagine
    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.PageNumberPagination",


    # Numero di oggetti restituiti per pagina
    "PAGE_SIZE": 20,


    # Classi usate per limitare la frequenza delle richieste (rate limiting)
    "DEFAULT_THROTTLE_CLASSES": [

        # Limite per utenti non autenticati (anonimi)
        "rest_framework.throttling.AnonRateThrottle",

        # Limite per utenti autenticati
        "rest_framework.throttling.UserRateThrottle",

    ],


    # Definisce i limiti di frequenza per ogni classe di throttling
    "DEFAULT_THROTTLE_RATES": {

        "anon": "100/day",   # Massimo 100 richieste al giorno per utenti anonimi
        "user": "1000/day",  # Massimo 1000 richieste al giorno per utenti autenticati

    },

}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
