# Generated by Django 6.0.5 on 2026-05-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=150)),
                ('nazionalita', models.TextField(blank=True, max_length=100)),
                ('biografia', models.TextField(blank=True)),
                ('data_debutto', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artisti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField(max_length=200)),
                ('anno', models.IntegerField()),
                ('genere', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classica', 'Classica'), ('Altro', 'Altro')], default='Altro', max_length=10, verbose_name='Genere')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='catalogo.artista')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
                'ordering': ['anno'],
            },
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField(max_length=200)),
                ('durata_secondi', models.IntegerField(verbose_name='Durata in secondi')),
                ('traccia', models.IntegerField(verbose_name='Numero di traccia')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canzoni', to='catalogo.album')),
            ],
            options={
                'verbose_name': 'Canzone',
                'verbose_name_plural': 'Canzoni',
                'ordering': ['traccia'],
            },
        ),
    ]
