# Generated by Django 6.0.5 on 2026-05-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_album_disponibile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artista', to='catalogo.artista'),
        ),
    ]
