# Generated by Django 6.0.5 on 2026-05-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_album_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='anno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anno'),
        ),
        migrations.CreateModel(
            name='ProfiloArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dettagli', models.TextField(blank=True)),
                ('artista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to='catalogo.artista')),
            ],
            options={
                'verbose_name': 'Profilo Artista',
                'verbose_name_plural': 'Profili Artisti',
                'ordering': ['artista__nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('album', models.ManyToManyField(blank=True, related_name='tags', to='catalogo.album')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
    ]
