# Generated by Django 6.0.5 on 2026-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_album_anno_profiloartista_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='album',
        ),
        migrations.AddField(
            model_name='canzone',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='canzoni', to='catalogo.tag'),
        ),
    ]
