# Generated by Django 6.0.5 on 2026-06-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_tag_album_canzone_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-anno'], 'verbose_name': 'Album', 'verbose_name_plural': 'Album'},
        ),
        migrations.AlterField(
            model_name='album',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nazionalita',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='canzone',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('autore', models.CharField(max_length=100)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='catalogo.canzone')),
            ],
            options={
                'verbose_name': 'Commento',
                'verbose_name_plural': 'Commenti',
                'ordering': ['-data_pubblicazione'],
            },
        ),
    ]
